### ISSUE TITLE
Current working directory (cwd) changes when I package the app

### ISSUE THREAD

**Issue by luisfpinto** [electron-userland/electron-packager#338]
When I runthe application and I show the current working directory It is where the app is running. 
However when I package the electron app with the electron-package the cwd changes to another one so my application crashes.

Any Idea how can I fix that?

> Which version of electron-packager are you using?
electron-packager@7.0.1

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

electron-packager dashboard Netbeast --platform=darwin --arch=x64 --version=0.37.2 --icon=dashboard/desktop_app/icon.icns --version-string.CompanyName=Netbeast --version-string.ProductName=NetbeastDashboard

> What version of [Electron](http://electron.atom.io) are you building with?

0.37.2

electron-prebuilt": "^0.37.2

> What is the host platform are you running electron-packager on?

Darwin 64 bits

> What target platform(s)/architecture(s) are you building for?

Darwin 64 bits

> Is there a stack trace in the error message you're seeing?

```
{ [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
fs.js:897
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/Users/luisf/public/img/favicon.png'
    at Error (native)
    at fs.statSync (fs.js:897:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:263:16)
    at favicon (/Users/luisf/Netbeast/Netbeast-darwin-x64/Netbeast.app/Contents/Resources/app/node_modules/serve-favicon/index.js:64:15)
    at Object.<anonymous> (/Users/luisf/Netbeast/Netbeast-darwin-x64/Netbeast.app/Contents/Resources/app/src/index.js:27:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/luisf/Netbeast/Netbeast-darwin-x64/Netbeast.app/Contents/Resources/app/index.js:16:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

> Please provide either a failing testcase or detailed steps to reproduce your problem.

1. Clone this:
```
git clone -b electron --single-branch https://github.com/netbeast/dashboard
```

2. Install packager
```
cd dashboard
npm i
```

3. Package
```
electron-packager dashboard Netbeast --platform=darwin --arch=x64 --version=0.37.6 --icon=dashboard/desktop_app/icon.icns --version-string.CompanyName=Netbeast --version-string.ProductName=NetbeastDashboard
```

4. Run and see the electron console.

**Comment by FelikZ** [comment]
On your `script.js`:
```js
var path = require('path');
var process = require('process');
console.log('cwd', process.cwd());
process.chdir(__dirname);
console.log('cwd', process.cwd());
```
