### ISSUE TITLE
electron-packager error while building

### ISSUE THREAD

**Issue by hos4m** [electron-userland/electron-packager#355]
Hello,

I'm pretty new to Electron and I'm using just the most basic configuration to try my first app using electron.

My package.json:
```
{
  "name": "github-electron",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "electron .",
    "build": "electron-packager . --all"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "electron-packager": "^7.0.1",
    "electron-prebuilt": "^0.37.8"
  }
}
```

when I run `npm run build`, I got this error (npm-debug.log content):
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@3.8.8
3 info using node@v0.12.7
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle github-electron@1.0.0~prebuild: github-electron@1.0.0
6 silly lifecycle github-electron@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle github-electron@1.0.0~build: github-electron@1.0.0
8 verbose lifecycle github-electron@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle github-electron@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/hosam/Dropbox/learning-workspace/github-electron/node_modules/.bin:/usr/local/bin:/Users/hosam/.rvm/gems/ruby-2.2.1/bin:/Users/hosam/.rvm/gems/ruby-2.2.1@global/bin:/Users/hosam/.rvm/rubies/ruby-2.2.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Users/hosam/.rvm/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin:/usr/local/mysql/bin
10 verbose lifecycle github-electron@1.0.0~build: CWD: /Users/hosam/Dropbox/learning-workspace/github-electron
11 silly lifecycle github-electron@1.0.0~build: Args: [ '-c', 'electron-packager . --version=0.36.9' ]
12 silly lifecycle github-electron@1.0.0~build: Returned: code: 1  signal: null
13 info lifecycle github-electron@1.0.0~build: Failed to exec build script
14 verbose stack Error: github-electron@1.0.0 build: `electron-packager . --version=0.36.9`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:244:16)
14 verbose stack     at EventEmitter.emit (events.js:110:17)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at ChildProcess.emit (events.js:110:17)
14 verbose stack     at maybeClose (child_process.js:1015:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
15 verbose pkgid github-electron@1.0.0
16 verbose cwd /Users/hosam/Dropbox/learning-workspace/github-electron
17 error Darwin 15.4.0
18 error argv "node" "/usr/local/bin/npm" "run" "build"
19 error node v0.12.7
20 error npm  v3.8.8
21 error code ELIFECYCLE
22 error github-electron@1.0.0 build: `electron-packager . --version=0.36.9`
22 error Exit status 1
23 error Failed at the github-electron@1.0.0 build script 'electron-packager . --version=0.36.9'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the github-electron package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron-packager . --version=0.36.9
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs github-electron
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls github-electron
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

What am I doing wrong?

Thank you.

**Comment by malept** [comment]
Your `package.json` differs from your output. `scripts.build` says it should run `electron-packager . --all` but according to your log it ran `electron-packager . --version=0.36.9`. The latter will not work because you need to specify either `--platform` and `--arch` (both require values), or `--all`.

If you run the command like so:

```shell
$(npm bin)/electron-packager . --version=0.36.9
```

It should tell you that it's missing the parameters I mentioned above. I don't know why running `npm run` commands don't show that.
