### ISSUE TITLE
Unable to find a valid app

### ISSUE THREAD

**Issue by nasht00** [electron-userland/electron-packager#369]
When running my application using `npm start`, everything works fine. However when trying to open the packaged version, I get:

```
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/Users/nathanh/Git/electron-verse/built/Verse-darwin-x64/Verse.app/Contents/Resources/electron.asar/browser/init.js:133:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:154:18)
    at node.js:416:3
```

My package.json:

```
{
  "name": "electron-verse",
  "version": "1.0.1",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "prepublish": "npm run build && npm run archive",
    "build": "electron-packager . Verse --platform=darwin --arch=x64 --version=1.0.1 --icon=./icons/icon.icns --overwrite --out=./built --ignore=\"(built|zipped|icons|README.md|package.json|npm-debug.log)\"",
    "archive": "mkdir -p ./zipped && rm -f ./zipped/electron-verse.zip && cd ./built && zip -r ../zipped/electron-verse.zip ./Verse-darwin-x64",
    "install-app": "rsync -delete -a -v ./built/Verse-darwin-x64/Verse.app /Applications"
  },
  "devDependencies": {
    "electron-packager": "latest",
    "electron-prebuilt": "1.0.1"
  }
}
```

> Which version of electron-packager are you using?

7.0.1

> What is the host platform are you running electron-packager on?
OSX 10.11.5

> What target platform(s)/architecture(s) are you building for?
darwin-x64

**Comment by nasht00** [comment]
OK I noticed that my `--ignore` had `package.json`. Removing this seems to fix the issue.  
Was this something that changed?

**Comment by malept** [comment]
Nope. Electron bundles have always needed `package.json`. Not sure why you added it to the `ignore` parameter.

**Comment by nasht00** [comment]
Apparently someone else introduced this ignore while I did not notice...

Sorry, false alert.
