### ISSUE TITLE
Windows 10 build error

### ISSUE THREAD

**Issue by mezaof** [electron-userland/electron-packager#372]
Helllo,

I'm newbie on node and electron family. I'm trying to build electron-quick-start but i'm getting error. I've try to install C++ addon but still can't building application. I can run application npm start but when i try to build with npm run build command i'm getting error like below.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild electron-quick-start@1.0.0
6 info build electron-quick-start@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info electron-quick-start@1.0.0 Failed to exec build script
9 verbose stack Error: electron-quick-start@1.0.0 build: `electron-packager main.js main`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid electron-quick-start@1.0.0
11 verbose cwd C:\Users\info\node\electron
12 error Windows_NT 10.0.10586
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.4.4
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error electron-quick-start@1.0.0 build: `electron-packager main.js main`
17 error Exit status 1
18 error Failed at the electron-quick-start@1.0.0 build script 'electron-packager main.js main'.
18 error This is most likely a problem with the electron-quick-start package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron-packager main.js main
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs electron-quick-start
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls electron-quick-start
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

My package.json is;

```
{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron main.js",
    "build": "electron-packager main.js main"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/electron/electron-quick-start.git"
  },
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "bugs": {
    "url": "https://github.com/electron/electron-quick-start/issues"
  },
  "homepage": "https://github.com/electron/electron-quick-start#readme",
  "devDependencies": {
    "electron-packager": "^7.0.2",
    "electron-prebuilt": "^1.0.1"
  }
}
```
OS: Windows 10 x64
npm ver: 2.15.1
node ver: v4.4.4

**Comment by malept** [comment]
You may want to read the [CLI usage documentation](https://github.com/electron-userland/electron-packager/blob/v7.0.2/usage.txt). Your build command is `electron-packager main.js main` - `main.js` is not a source directory and you're missing which platforms/architectures you are targeting to build application bundles.
