### ISSUE TITLE
Application build is failing

### ISSUE THREAD

**Issue by ErraticFox** [electron-userland/electron-packager#391]
First time creating a Electron app. I'm having trouble building it, as I'm getting errors.

> Which version of electron-packager are you using?

7.0.3

> What CLI arguments are you passing? Alternatively, if you are using the API, what parameters are
> you passing to the `packager()` function?

`"build": "electron-packager . Telar --platform=win32 --arch=all --version=3.9.5 --icon=app.ico --out=Staging --version-string.ProductName=Telar Converter --version-string.ProductVersion=0.5.0"
`
> What version of [Electron](http://electron.atom.io) are you building with?

3.9.5

> What is the host platform are you running electron-packager on?

Windows 10 x64

> What target platform(s)/architecture(s) are you building for?

Windows x86 and x64

> Is there a stack trace in the error message you're seeing?

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ErraticFox\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! electron@1.0.0 build: `electron-packager . Telar --platform=win32 --arch=all --version=7.0.3 --icon=app.ico --out=Staging --version-string.ProductName=Telar Converter --version-string.ProductVersion=0.5.0`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.0.0 build script 'electron-packager . Telar --platform=win32 --arch=all --version=7.0.3 --icon=app.ico --out=Staging --version-string.ProductName=Telar Converter --version-string.ProductVersion=0.5.0'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager . Telar --platform=win32 --arch=all --version=7.0.3 --icon=app.ico --out=Staging --version-string.ProductName=Telar Converter --version-string.ProductVersion=0.5.0
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ErraticFox\Documents\Electron\npm-debug.log
```
> Please provide either a failing testcase or detailed steps to reproduce your problem.

I run `npm run build` and get this error. Here's my debug log as well. Why is this happening?

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\ErraticFox\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.9.5
3 info using node@v6.2.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle electron@1.0.0~prebuild: electron@1.0.0
6 silly lifecycle electron@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle electron@1.0.0~build: electron@1.0.0
8 verbose lifecycle electron@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle electron@1.0.0~build: PATH: C:\Users\ErraticFox\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\ErraticFox\Documents\Electron\node_modules\.bin;C:\Program Files\nodejs;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\ffmpeg\binnn;C:\Users\ErraticFox\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\ErraticFox\AppData\Local\atom\bin;C:\Users\ErraticFox\AppData\Roaming\npm
10 verbose lifecycle electron@1.0.0~build: CWD: C:\Users\ErraticFox\Documents\Electron
11 silly lifecycle electron@1.0.0~build: Args: [ '/d /s /c',
11 silly lifecycle   'electron-packager . Telar --platform=win32 --arch=all --version=7.0.3 --icon=app.ico --out=Staging --version-string.ProductName=Telar Converter --version-string.ProductVersion=0.5.0' ]
12 silly lifecycle electron@1.0.0~build: Returned: code: 1  signal: null
13 info lifecycle electron@1.0.0~build: Failed to exec build script
14 verbose stack Error: electron@1.0.0 build: `electron-packager . Telar --platform=win32 --arch=all --version=7.0.3 --icon=app.ico --out=Staging --version-string.ProductName=Telar Converter --version-string.ProductVersion=0.5.0`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\ErraticFox\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\ErraticFox\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid electron@1.0.0
16 verbose cwd C:\Users\ErraticFox\Documents\Electron
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ErraticFox\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.2.1
20 error npm  v3.9.5
21 error code ELIFECYCLE
22 error electron@1.0.0 build: `electron-packager . Telar --platform=win32 --arch=all --version=7.0.3 --icon=app.ico --out=Staging --version-string.ProductName=Telar Converter --version-string.ProductVersion=0.5.0`
22 error Exit status 1
23 error Failed at the electron@1.0.0 build script 'electron-packager . Telar --platform=win32 --arch=all --version=7.0.3 --icon=app.ico --out=Staging --version-string.ProductName=Telar Converter --version-string.ProductVersion=0.5.0'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the electron package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron-packager . Telar --platform=win32 --arch=all --version=7.0.3 --icon=app.ico --out=Staging --version-string.ProductName=Telar Converter --version-string.ProductVersion=0.5.0
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs electron
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls electron
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by malept** [comment]
`--version` refers to the Electron version, not the application version (or the electron-packager version). For the application version, use `--app-version`.

**Comment by ErraticFox** [comment]
When I do `electron-packager . --all` it still outputs the same thing though.

**Comment by malept** [comment]
Could you run that command outside of npm and post the output? NPM likes to hide the useful output.

**Comment by ErraticFox** [comment]
Does that mean I'd have to install the CLI version?

**Comment by malept** [comment]
You already have it installed, run `node_modules\.bin\electron-packager . --all`

**Comment by ErraticFox** [comment]
I get

```
C:\Users\ErraticFox\Documents\Electron>node_modules\.bin\electron-packager . --all
Unable to infer name or version. Please specify a name and version.
Cannot find module 'package.json' from 'C:\Users\ErraticFox\Documents'(Properties not found yet: dependencies.electron-prebuilt,devDependencies.electron-prebuilt)
```

**Comment by malept** [comment]
You need to specify the Electron version either via `--version` in the command line or in your `package.json`, adding `electron-prebuilt (with a version)` to the `devDependencies`.

**Comment by ErraticFox** [comment]
Alright, it runs it looks like.

`Packaging app for platform linux ia32 using electron v1.2.2
EEXIST: file already exists, link 'C:\Users\ERRATI~1\AppData\Local\Temp\electron-packager\linux-ia32\electron-linux-ia32\electron' -> 'C:\Users\ERRATI~1\AppData\Local\Temp\electron-packager\linux-ia32\electron-linux-ia32\electron'`

**Comment by malept** [comment]
You want to clear your temporary directory (it failed halfway so it probably didn't clean up after itself correctly).
