### ISSUE TITLE
Errors in electron-packager\common.js

### ISSUE THREAD

**Issue by hussainb** [electron-userland/electron-packager#411]
The following errors are thrown when building a package using the command:

```
E:\electron>electron-packager "E:\electron\electron-quick-star
t-master" "QuickStart" --platform=win32 --arch=x64
```

```
C:\Users\hussain\AppData\Roaming\npm\node_modules\electron-packager\common.js:3
const asar = require('asar')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\hussain\AppData\Roaming\npm\node_modules\ele
ctron-packager\cli.js:5:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

After remarking the `'use strict'` statement from common.js, the following errors were thrown:

```
C:\Users\hussain\AppData\Roaming\npm\node_modules\electron-packager\common.js:67

  return `${opts.name}-${opts.platform}-${opts.arch}`
         ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\hussain\AppData\Roaming\npm\node_modules\ele
ctron-packager\cli.js:5:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

After fixing the single quotes, other code blocks with similar single quote issues came up.

**Comment by malept** [comment]
It appears that you're running Node < 4.0.

Node 4.0 or greater is required as of electron-packager 7.0.0, per:

* [the NEWS file](https://github.com/electron-userland/electron-packager/blob/v7.0.0/NEWS.md#700---2016-04-17)
* [the installation instructions](https://github.com/electron-userland/electron-packager#installation)
* the [`engines` section of `package.json`](https://github.com/electron-userland/electron-packager/blob/v7.0.0/package.json#L42-L44)

**Comment by hussainb** [comment]
Oops, Thankyou
