### ISSUE TITLE
Error on pack

### ISSUE THREAD

**Issue by Astolfoho** [electron-userland/electron-packager#427]
I trying to build a package but i can't, because this eror

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'win-bundle' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prewin-bundle', 'win-bundle', 'postwin-bundle' ]
5 info lifecycle electron-quick-start@1.0.0~prewin-bundle: electron-quick-start@1.0.0
6 silly lifecycle electron-quick-start@1.0.0~prewin-bundle: no script for prewin-bundle, continuing
7 info lifecycle electron-quick-start@1.0.0~win-bundle: electron-quick-start@1.0.0
8 verbose lifecycle electron-quick-start@1.0.0~win-bundle: unsafe-perm in lifecycle true
9 verbose lifecycle electron-quick-start@1.0.0~win-bundle: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin;c:\Users\ahoscher\Source\Repos\electron-quick-start\node_modules\.bin;C:\Program Files (x86)\nodejs;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft Team Foundation Server 2010 Power Tools\Best Practices Analyzer\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\Microchip\xc8\v1.37\bin;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\ahoscher\AppData\Roaming\npm;C:\Program Files\GPAC;C:\Program Files\GPAC;C:\Program Files\GPAC
10 verbose lifecycle electron-quick-start@1.0.0~win-bundle: CWD: c:\Users\ahoscher\Source\Repos\electron-quick-start
11 silly lifecycle electron-quick-start@1.0.0~win-bundle: Args: [ '/d /s /c', 'electron-packager --platform=win32 --arch=ia32' ]
12 silly lifecycle electron-quick-start@1.0.0~win-bundle: Returned: code: 1  signal: null
13 info lifecycle electron-quick-start@1.0.0~win-bundle: Failed to exec win-bundle script
14 verbose stack Error: electron-quick-start@1.0.0 win-bundle: `electron-packager --platform=win32 --arch=ia32`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid electron-quick-start@1.0.0
16 verbose cwd c:\Users\ahoscher\Source\Repos\electron-quick-start
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "win-bundle"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error electron-quick-start@1.0.0 win-bundle: `electron-packager --platform=win32 --arch=ia32`
22 error Exit status 1
23 error Failed at the electron-quick-start@1.0.0 win-bundle script 'electron-packager --platform=win32 --arch=ia32'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the electron-quick-start package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron-packager --platform=win32 --arch=ia32
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs electron-quick-start
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls electron-quick-start
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by malept** [comment]
If you run the electron-packager command without using "npm run", you should get an appropriate error message. In this case, you're not specifying your application directory.
