### ISSUE TITLE
Issues with packaged native modules (On windows/osx, not linux)

### ISSUE THREAD

**Issue by robogen** [electron-userland/electron-packager#520]
A current package I'm working on requires the use of native packaging. One of the features of it is that it collects information about local disk usage (using [diskusage](https://github.com/jduncanator/node-diskusage)) to inform the user as they download data. Two of the dependencies of the diskusage package ([ref](https://github.com/TooTallNate/ref) and [ffi](https://github.com/node-ffi/node-ffi)) are native modules and require compiling and by default don't work without using electron-rebuild.

If I perform an 'npm run' in my app directory, the application runs perfectly fine with no complaints on OSX/Windows/Linux. However, after running electron-packager, it only works on Linux. For Windows/OSX it breaks as soon as it attempts to access the ref package. It complains with a message of "expected module 50, got 49" but I'm not 100% on where it's getting those numbers.

Using node version 6.9.1

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Nothing other than 'Wrote new app to <directory>'
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
node ./node_modules/electron-packager/cli.js ./ <appname> --platform=win32 --arch=all --out ../packageWin/ --version 1.4.3 --overwrite --icon ./icons/<appname>
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem.**

in the same folder where my 'app' directory is I have a 'postinstall.js' script with the content of 

```
#!/usr/bin/env node
var exec = require('child_process').exec;

exec('./node_modules/.bin/electron-rebuild -w ffi',
    function(error,stdout,stderr){
    
    });

exec('./node_modules/.bin/electron-rebuild -w ref',
    function(error,stdout,stderr){
    
    });
```

With slight modification on Windows, so it uses electron-rebuild.cmd and strong paths instead. After running an npm install, the app installs fine with no errors and runs fine after 'npm run' no matter what (in terms of no packages crashing). Once I run the aforementioned packing command, I can launch and run the application and be fine on Linux, but on Win32/OSX I'm only fine until I open the page with the require('diskusage') command in it. As soon as it hits that line, bindings.js shows the 'expected 50, got 49' error.

As a side note, I'm building the Linux package on a Linux machine, Windows on Windows(7), and OSX on OSX.

**Comment by malept** [comment]
CC: @MarshallOfSound since he has more experience with electron-rebuild.

**Comment by MarshallOfSound** [comment]
@robogen I had to do some interesting things to get `electron_rebuild` working from within a JS script.  Basically two things come to mind when I think back to how I made it work.

1. Use `spawn` not `exec`
2. Ensure you set the `cwd` value correctly, it has to be the folder that contains your project (not a sub-folder but the top level)

For an example see --> https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/vendor/rebuild.js#L24

In the latest `electron-rebuild` you can get extended output (and see what is actually happening) by using the `--log` argument

**Comment by robogen** [comment]
@MarshallOfSound Thank you for the help, the extra log output has helped a bit! Unfortunately, I'm still getting that 'Expected module version 50, got version 49' error when the 'diskusage' package gets called. (apologies on not posting this stack earlier!)
```
Error: Module version mismatch. Expected 50, got 49.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (C:\Users\<user>\Documents\GitHub\<app>\packageWin\<app>-win32-x64\resources\app\node_modules\bindings\bindings.js:76:44) <div ng-view="" class="ng-scope">
```

This is my new postinstall.js
```
#!/usr/bin/env node
const spawn = require('child_process').spawn;
const ref = spawn(__dirname + '\\node_modules\\.bin\\electron-rebuild.cmd',
                  ['-w', 'ffi', '--log'],
                  { cwd: __dirname,
                    env: process.env});
const ffi = spawn(__dirname + '\\node_modules\\.bin\\electron-rebuild.cmd',
                  ['-w', 'ref', '--log'],
                  { cwd: __dirname,
                    env: process.env});

ref.stdout.on('data', (data) => {
    console.log(`refout: ${data}`);
});

ref.stderr.on('data', (data) => {
    console.log(`referr: ${data}`);
});

ref.on('close', (code) => {
    if (code !== 0) {
        console.log(`ref rebuild exited with code ${code}`);
    }
});

ffi.stdout.on('data', (data) => {
    console.log(`ffiout: ${data}`);
});

ffi.stderr.on('data', (data) => {
    console.log(`ffierr: ${data}`);
});

ffi.on('close', (code) => {
    if (code !== 0) {
        console.log(`ffi rebuild exited with code ${code}`);
    }
});
```

**Comment by MarshallOfSound** [comment]
@robogen Can you see the modules actually rebuild in the logs.  If not something is wrong with your rebuild command.  I'd suggest removing the `-w` are and values.

**Comment by robogen** [comment]
@MarshallOfSound Yes, the output seems to indicate they're properly rebuilding. With the -w flag this is the output (produced on Windows)
```
ffiout:
> ref@1.3.2 install C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref
> node-gyp rebuild


refout:
> ffi@2.2.0 install C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi
> node-gyp rebuild


refout:
C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi>if
refout: not defined npm_config_node_gyp (node "C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

ffiout:

ffiout: C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

refout: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

ffiout: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

refout:   Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm

ffiout:   binding.cc

ffiout:   win_delay_load_hook.cc

refout:    Assembling: ..\..\..\deps\libffi\src\x86\win64.asm

refout:   prep_cif.c

refout:   types.c

refout:   raw_api.c

refout:   java_raw_api.c

refout:   closures.c

refout:   ffi.c

refout:   win_delay_load_hook.cc

refout:   ffi.vcxproj -> C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\Release\\libffi.lib

refout:   ffi.cc

refout:   callback_info.cc
  threaded_callback_invokation.cc

refout:   win32-dlfcn.cc

refout:   win_delay_load_hook.cc

ffiout: ..\src\binding.cc(643): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref\build\binding.vcxproj]

ffiout:   C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

ffiout: ..\src\binding.cc(644): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref\build\binding.vcxproj]

ffiout:   C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

ffiout:      Creating library C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref\build\Release\binding.lib and object C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref\build\Release\binding.exp

ffiout:   Generating code

refout: ..\src\ffi.cc(111): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\ffi_bindings.vcxproj]

refout:   C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'
..\src\ffi.cc(114): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\ffi_bindings.vcxproj]

refout:   C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

refout: ..\src\ffi.cc(123): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\ffi_bindings.vcxproj]

refout:   C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

refout: ..\src\ffi.cc(124): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\ffi_bindings.vcxproj]

refout:   C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

refout: ..\src\ffi.cc(125): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\ffi_bindings.vcxproj]

refout:   C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

refout: ..\src\ffi.cc(126): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\ffi_bindings.vcxproj]

refout:   C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

refout: ..\src\ffi.cc(132): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\ffi_bindings.vcxproj]

refout:   C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

ffiout:   Finished generating code

ffiout:   binding.vcxproj -> C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref\build\Release\\binding.node

ffiout:   binding.vcxproj -> C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref\build\Release\binding.pdb (Full PDB)

ffiout: ref@1.3.2 C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref

refout:      Creating library C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\Release\ffi_bindings.lib and object C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\Release\ffi_bindings.exp

refout:   Generating code

refout:   Finished generating code

refout:   ffi_bindings.vcxproj -> C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\Release\\ffi_bindings.node

refout:   ffi_bindings.vcxproj -> C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\Release\ffi_bindings.pdb (Full PDB)

refout: ffi@2.2.0 C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi
```

I'll try removing the -w and seeing if that makes the difference.

**Comment by robogen** [comment]
That seems to have made the difference, though I have some new errors to deal with

```
ffierr: npm
ffierr:  ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\<user>\\Documents\\GitHub\\<app>\\<app>\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--runtime=electron" "--target=1.3.8" "--arch=x64" "--update-binary"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! path C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\.bin\uuid
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\.bin\uuid'
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\.bin\uuid'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

ffierr:

ffierr: npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\npm-debug.log

ffierr: Process exited with code: 4294963238

ffierr: Error: Process exited with code: 4294963238
    at ChildProcess.<anonymous> (C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\spawn.js:55:26)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

ffi rebuild exited with code 4294967295
refout:
> ffi@2.2.0 install C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi
> node-gyp rebuild


refout:
C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi>if
refout: not defined npm_config_node_gyp (node "C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

refout: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

refout:   Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm

refout:    Assembling: ..\..\..\deps\libffi\src\x86\win64.asm

refout:   prep_cif.c

refout:   types.c

refout:   raw_api.c

refout:   java_raw_api.c

refout:   closures.c

refout:   ffi.c

refout:   win_delay_load_hook.cc

refout:   ffi.vcxproj -> C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\Release\\libffi.lib

refout:   ffi.cc

refout:   callback_info.cc

refout:   threaded_callback_invokation.cc

refout:   win32-dlfcn.cc

refout:   win_delay_load_hook.cc

refout: ..\src\ffi.cc(111): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\ffi_bindings.vcxproj]
  C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

refout: ..\src\ffi.cc(114): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\ffi_bindings.vcxproj]
  C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

refout: ..\src\ffi.cc(123): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\ffi_bindings.vcxproj]

refout:   C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

refout: ..\src\ffi.cc(124): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\ffi_bindings.vcxproj]
  C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

refout: ..\src\ffi.cc(125): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\ffi_bindings.vcxproj]

refout:   C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

refout: ..\src\ffi.cc(126): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\ffi_bindings.vcxproj]

refout:   C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

refout: ..\src\ffi.cc(132): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\ffi_bindings.vcxproj]

refout:   C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

refout:      Creating library C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\Release\ffi_bindings.lib and object C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\Release\ffi_bindings.exp

refout:   Generating code

refout:   Finished generating code

refout:   ffi_bindings.vcxproj -> C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\Release\\ffi_bindings.node

refout:   ffi_bindings.vcxproj -> C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ffi\build\Release\ffi_bindings.pdb (Full PDB)

refout:
> ref@1.3.2 install C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref
> node-gyp rebuild


refout:
C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref>
refout: if not defined npm_config_node_gyp (node "C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

refout: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

refout:   binding.cc

refout:   win_delay_load_hook.cc

refout: ..\src\binding.cc(643): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref\build\binding.vcxproj]

refout:   C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

refout: ..\src\binding.cc(644): warning C4996: 'v8::Object::ForceSet': was declared deprecated [C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref\build\binding.vcxproj]
  C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.3.8\deps\v8\include\v8.h(2687): note: see declaration of 'v8::Object::ForceSet'

refout:      Creating library C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref\build\Release\binding.lib and object C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref\build\Release\binding.exp

refout:   Generating code

refout:   Finished generating code

refout:   binding.vcxproj -> C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref\build\Release\\binding.node

refout:   binding.vcxproj -> C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\ref\build\Release\binding.pdb (Full PDB)

referr: npm
referr:  WARN prefer global marked@0.3.6 should be installed with -g

refout:
> electron-prebuilt@1.3.8 postinstall C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-prebuilt
> node install.js


refout:
> nslog@3.0.0 install C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\nslog
> node-gyp rebuild


refout:
C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\nslog>
refout: if not defined npm_config_node_gyp (node "C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

referr: gyp
referr:  ERR! clean error

referr: gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\nslog\build\Release\nslog.node'
gyp ERR! stack     at Error (native)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\<user>\\Documents\\GitHub\\<app>\\<app>\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\nslog
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

referr:

referr: npm ERR! Windows_NT 6.1.7601
npm ERR!
referr:  argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\<user>\\Documents\\GitHub\\<app>\\<app>\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--runtime=electron" "--target=1.3.8" "--arch=x64" "--update-binary"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

referr:
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\npm-debug.log

referr: Process exited with code: 1

referr: Error: Process exited with code: 1
    at ChildProcess.<anonymous> (C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\electron-rebuild\lib\spawn.js:55:26)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by robogen** [comment]
@MarshallOfSound After grabbing the packages 'uuid' and 'asar' it's now failing on 

for ffi
```
Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
```

for ref
```
referr: ERR! clean error
gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\nslog\build\Release\nslog.node'
```

Why does it give these error messages now though, without the -w? How does electron-rebuild handle them differently, or does it suppress warnings the first method? And why did it work before while it wasn't packaged but broke once it was?

**Comment by MarshallOfSound** [comment]
> And why did it work before while it wasn't packaged but broke once it was?

You'll be packaging for a different arch than your node install

> gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Users\<user>\Documents\GitHub\<app>\<app>\node_modules\nslog\build\Release\nslog.node'

Yeah, nslog is a nightmare.  On windows I have `rmdir /Q /S nslog\build 2>nul` before I run the rebuild.

**Comment by robogen** [comment]
@MarshallOfSound I don't think I can say thank you enough, it's finally working now! Here's the new postinstall.js
```
#!/usr/bin/env node
const spawn = require('child_process').spawnSync;
const fs = require('fs');
var rebuilder = "";
const target = "1.4.3";

if (process.platform == 'win32') {
    rebuilder = "electron-rebuild.cmd";
} else {
    rebuilder = "electron-rebuild";
}

// nslog fixer
fs.unlinkSync(__dirname + '\\node_modules\\nslog\\build\\Release\\nslog.node');

const ref = spawn(__dirname + '\\node_modules\\.bin\\' + rebuilder,
                  ['--version='+target,'--log'],
		  { cwd: __dirname + '\\node_modules\\ref',
		    env: process.env,
			shell: true });
console.log('ref output: ' + ref.output);
console.log('ref error: ' + ref.error);

const ffi = spawn(__dirname + '\\node_modules\\.bin\\' + rebuilder,
                  ['--version='+target,'--log'],
		  { cwd: __dirname + '\\node_modules\\ffi',
		    env: process.env,
			shell: true });
console.log('ffi output: ' + ffi.output);
console.log('ffi error: ' + ffi.error);
```

I had trouble with exec not working with your rmdir command, but I substituted it for the fs.unlinkSync command and it's working great now. A hurdle that was giving me trouble was the spawn command, I didn't realize fully at first that it was an asynchronous command. With both the ref and the ffi spawned commands running, they were both attempting to access the same files in nslog at the same time, switching them to be synchronous fixed that however. With this new script it works perfect!

Once again, thank you for the assistance!
