### ISSUE TITLE
arch parameter does not handle non-arrays/strings gracefully

### ISSUE THREAD

**Issue by dcrystalj** [electron-userland/electron-packager#533]
running this makes error
```
➜  electron-quick-start git:(master) electron-packager . --platform=Linux --arch=64
/usr/local/lib/node_modules/electron-packager/targets.js:26
    if (!Array.isArray(list)) list = list.split(',')
                                          ^

TypeError: list.split is not a function
    at Object.validateListFromOptions (/usr/local/lib/node_modules/electron-packager/targets.js:26:43)
    at packager (/usr/local/lib/node_modules/electron-packager/index.js:234:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-packager/cli.js:30:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

```
➜  electron-quick-start git:(master) npm -v
3.10.8
➜  electron-quick-start git:(master) node -v
v6.9.1
```

**Comment by malept** [comment]
64 is not a valid arch. You probably want x64. That being said, there should be a better error for type errors.

**Comment by dcrystalj** [comment]
lool, spent one hour for this. Thank you

also Linux should not be capitalised! :-1:
