### ISSUE TITLE
Blocked Scope error when I package my app with platform mas

### ISSUE THREAD

**Issue by AhadCove** [electron-userland/electron-packager#554]
When I package my app with platform mas, I get this error:
```
Uncaught Exception:
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (../Path/App-mas-x64/App.app/Contents/Resources/atom.asar/browser/lib/init.js:152:8)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)

```
This error does not reproduce for any other platform I use. Will I have to go in and take out all my lets and const?

**Comment by MarshallOfSound** [comment]
@AhadCove Which electron version is this?

**Comment by AhadCove** [comment]
This is version 0.36.7

**Comment by MarshallOfSound** [comment]
@AhadCove I believe a version that old is running on `node.js` version 4.x where as the error message says in order to use some ES6 features you need to add

```js
'use strict';
```

to the top of all your files.  You should probably just upgrade to Electron `1.4.x` which uses node.js `v6` and doesn't have this requirement.

This issue was probably a raised issue with Electron back when `0.36` and no longer affects up to date Electron versions.
