### ISSUE TITLE
CI failure on Node 5 + OSX: MAS app cannot be built (missing plist file)

### ISSUE THREAD

**Issue by malept** [electron-userland/electron-packager#598]
* [X] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

https://travis-ci.org/electron-userland/electron-packager/jobs/203239814#L2186

Context provided, just in case the test log goes away:

```
# setup
# all test
  electron-packager Electron Packager 8.5.1 +48ms
  electron-packager Node v5.12.0 +0ms
  electron-packager Host Operating system: darwin (x64) +0ms
  electron-packager Packager Options: {"name":"basicTest","dir":"/Users/travis/build/electron-userland/electron-packager/test/fixtures/basic","electronVersion":"0.35.6","all":true} +2ms
  electron-packager Target Platforms: darwin, linux, mas, win32 +2ms
  electron-packager Target Architectures: ia32, x64, armv7l +0ms
  electron-packager Inferring app-version from version in /Users/travis/build/electron-userland/electron-packager/test/fixtures/basic/package.json +14ms
  electron-packager Application name: basicTest +2ms
  electron-packager Target Electron version: 0.35.6 +0ms
  electron-packager Ignored path regular expressions: [ '/node_modules/electron($|/)',
  '/node_modules/electron-prebuilt($|/)',
  '/node_modules/electron-packager($|/)',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$' ] [32m+2ms
  electron-packager Downloading Electron with options {"platform":"linux","arch":"ia32","version":"0.35.6"} +6ms
Packaging app for platform linux ia32 using electron v0.35.6
  electron-packager Creating /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/linux-ia32-template +7ms
  electron-packager Extracting /Users/travis/.electron/electron-v0.35.6-linux-ia32.zip to /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/linux-ia32-template +2ms
  electron-packager Initializing app in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/linux-ia32/basicTest-linux-ia32 from /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/linux-ia32-template template +2s
  electron-packager Ignored paths based on the out param: [ '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-darwin-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-darwin-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-darwin-armv7l',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-armv7l',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-mas-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-mas-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-mas-armv7l',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-win32-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-win32-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-win32-armv7l' ] +9ms
  electron-packager Running npm prune --production +2s
  electron-packager Renaming electron to basicTest in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/linux-ia32/basicTest-linux-ia32 +3s
  electron-packager Moving /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/linux-ia32/basicTest-linux-ia32 to /Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-ia32 +2ms
  electron-packager Downloading Electron with options {"platform":"win32","arch":"ia32","version":"0.35.6"} +4ms
Packaging app for platform win32 ia32 using electron v0.35.6
  electron-packager Creating /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/win32-ia32-template +14ms
  electron-packager Extracting /Users/travis/.electron/electron-v0.35.6-win32-ia32.zip to /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/win32-ia32-template +1ms
  electron-packager Initializing app in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/win32-ia32/basicTest-win32-ia32 from /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/win32-ia32-template template +2s
  electron-packager Ignored paths based on the out param: [ '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-darwin-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-darwin-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-darwin-armv7l',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-armv7l',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-mas-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-mas-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-mas-armv7l',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-win32-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-win32-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-win32-armv7l' ] +4ms
  electron-packager Running npm prune --production +2s
  electron-packager Renaming electron.exe to basicTest.exe in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/win32-ia32/basicTest-win32-ia32 +3s
  electron-packager Running rcedit with the options {"version-string":{},"file-version":"4.99.101","product-version":"4.99.101"} +3ms
  electron-packager Moving /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/win32-ia32/basicTest-win32-ia32 to /Users/travis/build/electron-userland/electron-packager/test/work/basicTest-win32-ia32 +5s
  electron-packager Downloading Electron with options {"platform":"darwin","arch":"x64","version":"0.35.6"} +3ms
Packaging app for platform darwin x64 using electron v0.35.6
  electron-packager Creating /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/darwin-x64-template +21ms
  electron-packager Extracting /Users/travis/.electron/electron-v0.35.6-darwin-x64.zip to /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/darwin-x64-template +2ms
  electron-packager Initializing app in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/darwin-x64/basicTest-darwin-x64 from /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/darwin-x64-template template +3s
  electron-packager Ignored paths based on the out param: [ '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-darwin-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-darwin-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-darwin-armv7l',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-armv7l',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-mas-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-mas-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-mas-armv7l',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-win32-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-win32-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-win32-armv7l' ] +9ms
  electron-packager Running npm prune --production +2s
  electron-packager Renaming Electron to basicTest in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/darwin-x64/basicTest-darwin-x64/Electron.app/Contents/MacOS +3s
  electron-packager Renaming Electron Helper to basicTest Helper in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/darwin-x64/basicTest-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS +6ms
  electron-packager Renaming Electron Helper.app to basicTest Helper.app in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/darwin-x64/basicTest-darwin-x64/Electron.app/Contents/Frameworks +5ms
  electron-packager Renaming Electron Helper EH to basicTest Helper EH in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/darwin-x64/basicTest-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper EH.app/Contents/MacOS +2ms
  electron-packager Renaming Electron Helper EH.app to basicTest Helper EH.app in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/darwin-x64/basicTest-darwin-x64/Electron.app/Contents/Frameworks +5ms
  electron-packager Renaming Electron Helper NP to basicTest Helper NP in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/darwin-x64/basicTest-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper NP.app/Contents/MacOS +4ms
  electron-packager Renaming Electron Helper NP.app to basicTest Helper NP.app in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/darwin-x64/basicTest-darwin-x64/Electron.app/Contents/Frameworks +3ms
  electron-packager Moving /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/darwin-x64/basicTest-darwin-x64 to /Users/travis/build/electron-userland/electron-packager/test/work/basicTest-darwin-x64 +3ms
  electron-packager Downloading Electron with options {"platform":"linux","arch":"x64","version":"0.35.6"} +3ms
Packaging app for platform linux x64 using electron v0.35.6
  electron-packager Creating /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/linux-x64-template +6ms
  electron-packager Extracting /Users/travis/.electron/electron-v0.35.6-linux-x64.zip to /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/linux-x64-template +4ms
  electron-packager Initializing app in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/linux-x64/basicTest-linux-x64 from /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/linux-x64-template template +2s
  electron-packager Ignored paths based on the out param: [ '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-darwin-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-darwin-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-darwin-armv7l',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-armv7l',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-mas-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-mas-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-mas-armv7l',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-win32-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-win32-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-win32-armv7l' ] +4ms
  electron-packager Running npm prune --production +1s
  electron-packager Renaming electron to basicTest in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/linux-x64/basicTest-linux-x64 +3s
  electron-packager Moving /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/linux-x64/basicTest-linux-x64 to /Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-x64 +2ms
  electron-packager Downloading Electron with options {"platform":"mas","arch":"x64","version":"0.35.6"} +3ms
Packaging app for platform mas x64 using electron v0.35.6
  electron-packager Creating /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/mas-x64-template +11ms
  electron-packager Extracting /Users/travis/.electron/electron-v0.35.6-mas-x64.zip to /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/mas-x64-template +1ms
  electron-packager Initializing app in /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/mas-x64/basicTest-mas-x64 from /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/mas-x64-template template +68ms
  electron-packager Ignored paths based on the out param: [ '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-darwin-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-darwin-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-darwin-armv7l',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-linux-armv7l',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-mas-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-mas-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-mas-armv7l',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-win32-ia32',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-win32-x64',
  '/Users/travis/build/electron-userland/electron-packager/test/work/basicTest-win32-armv7l' ] +3ms
  electron-packager Running npm prune --production +2s
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/electron-packager/mas-x64/basicTest-mas-x64/Electron.app/Contents/Info.plist'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at MacApp.loadPlist (/Users/travis/build/electron-userland/electron-packager/mac.js:1:23260)
    at MacApp.updatePlistFiles (/Users/travis/build/electron-userland/electron-packager/mac.js:1:23897)
    at buildMacApp (/Users/travis/build/electron-userland/electron-packager/mac.js:13:803)
    at /Users/travis/build/electron-userland/electron-packager/common.js:23:24
    at end (/Users/travis/build/electron-userland/electron-packager/node_modules/run-series/index.js:8:15)
    at done (/Users/travis/build/electron-userland/electron-packager/node_modules/run-series/index.js:11:10)
    at each (/Users/travis/build/electron-userland/electron-packager/node_modules/run-series/index.js:16:43)
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:484:12)
```

Note that the darwin build works fine.

**Comment by malept** [comment]
Evidently this doesn't happen all of the time 😕 

https://travis-ci.org/electron-userland/electron-packager/jobs/205659321

**Comment by malept** [comment]
I haven't seen this in over a month, so I'm inclined to revert #599 and close this.
