### ISSUE TITLE
"Array buffer allocation failed" error when building for armv7l on raspberrypi3

### ISSUE THREAD

**Issue by criticalboot** [electron-userland/electron-packager#638]
Hi,
 When I tried to build electron app for raspberrypi3 getting the following error.

* [x ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
electron-packager Electron Packager 8.3.0 +0ms
  electron-packager Node v6.5.0 +14ms
  electron-packager Host Operating system: linux (arm) +7ms
  electron-packager Packager Options: {"_":["./"],"all":false,"deref-symlinks":true,"download":{"strictSSL":true},"overwrite":false,"prune":true,"arch":"armv7l","dir":"./","protocols":[]} +1ms
  electron-packager Target Platforms: linux +2ms
  electron-packager Target Architectures: armv7l +1ms
  electron-packager Inferring application name from name in /home/pi/OmniCoMM_src/package.json +74ms
  electron-packager Inferring app-version from version in /home/pi/OmniCoMM_src/package.json +0ms
  electron-packager Inferring target Electron version from electron in /home/pi/OmniCoMM_src/package.json +21ms
  electron-packager Application name: zonecontrolserver +1ms
  electron-packager Target Electron version: 1.4.13 +0ms
  electron-packager Ignored path regular expressions: [ '/node_modules/electron($|/)',
  '/node_modules/electron-prebuilt($|/)',
  '/node_modules/electron-packager($|/)',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$' ] +1ms
 electron-packager Downloading Electron with options {"strictSSL":true,"platform":"linux","arch":"armv7l","version":"1.4.13"} +2m
Packaging app for platform linux armv7l using electron v1.4.13
  electron-packager Creating /tmp/electron-packager/linux-armv7l-template +2s
  electron-packager Extracting /home/pi/.electron/electron-v1.4.13-linux-armv7l.zip to /tmp/electron-packager/linux-armv7l-template +4ms
  electron-packager Initializing app in /tmp/electron-packager/linux-armv7l/zonecontrolserver-linux-armv7l from /tmp/electron-packager/linux-armv7l-template template +42s
  electron-packager Ignored paths based on the out param: [ '/home/pi/OmniCoMM_src/zonecontrolserver-darwin-ia32',
  '/home/pi/OmniCoMM_src/zonecontrolserver-darwin-x64',
  '/home/pi/OmniCoMM_src/zonecontrolserver-darwin-armv7l',
  '/home/pi/OmniCoMM_src/zonecontrolserver-linux-ia32',
  '/home/pi/OmniCoMM_src/zonecontrolserver-linux-x64',
  '/home/pi/OmniCoMM_src/zonecontrolserver-linux-armv7l',
  '/home/pi/OmniCoMM_src/zonecontrolserver-mas-ia32',
  '/home/pi/OmniCoMM_src/zonecontrolserver-mas-x64',
  '/home/pi/OmniCoMM_src/zonecontrolserver-mas-armv7l',
  '/home/pi/OmniCoMM_src/zonecontrolserver-win32-ia32',
  '/home/pi/OmniCoMM_src/zonecontrolserver-win32-x64',
  '/home/pi/OmniCoMM_src/zonecontrolserver-win32-armv7l' ] +2s
buffer.js:8
class FastBuffer extends Uint8Array {}
^

RangeError: Array buffer allocation failed
    at Buffer.Uint8Array (native)
    at FastBuffer (buffer.js:8:1)
    at createUnsafeBuffer (buffer.js:33:12)
    at allocate (buffer.js:176:12)
    at Function.Buffer.allocUnsafe (buffer.js:136:10)
    at allocNewPool (fs.js:1844:17)
    at ReadStream._read (fs.js:1944:5)
    at ReadStream.Readable.read (_stream_readable.js:348:10)
    at /home/pi/OmniCoMM_src/node_modules/graceful-fs/graceful-fs.js:194:14
    at /home/pi/OmniCoMM_src/node_modules/graceful-fs/graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
node_modules/.bin/electron-packager ./ --arch=armv7l
```

**
building for raspberrypi3
**

**Comment by malept** [comment]
It sounds like the Raspberry Pi 3 (or at least yours) doesn't have enough memory to build an Electron app. I suggest building it on a different computer (any of Windows/macOS/Linux on x86/x64 architectures), and just specify the target platform as `linux` and the target `arch` the same as you're doing right now.
