### ISSUE TITLE
App works, but packaged electron-app displays JavaScript error only

### ISSUE THREAD

**Issue by wende60** [electron-userland/electron-packager#646]
hi there,

creating a little Electron test-app based on react, sass and pouchdb. 
The App works, but after creating a package the Electron-app opens with an error:

A JavaScript error occurred in the main process

Uncaught Exception:
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Object.<anonymous> (/Users/joachim/work/test/timeTracker/bin/ElectronReactSass-darwin-x64/ElectronReactSass.app/Contents/Resources/atom.asar/browser/lib/init.js:123:10)
    at Object.<anonymous> (/Users/joachim/work/test/timeTracker/bin/ElectronReactSass-darwin-x64/ElectronReactSass.app/Contents/Resources/atom.asar/browser/lib/init.js:125:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)

you can find the code here:
https://github.com/wende60/timeTracker

Forgive me, the code is in progress ;)

babel-cli is installed globally and updated to the latest version, so is node and npm. 
running 'build' and then 'start', or running 'watch' works fine. 
Running 'bin' to pack results in the above error.

I find it hard to debug here, no idea what conflicts i have. Tested to update some loaders and electron to 1.6.8 did not help. Other similar issues did not give a solution. 

Any hints for me?

Thanks and regards, jo

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
That said you packager script has this ` --version=0.34.0` which is a **really** old electron version, update that version and it should start working 👍

**Comment by wende60** [comment]
This was left over, and not updated with the electron install, thanks for the hint, it works :)
