### ISSUE TITLE
Electron rebuilding problem

### ISSUE THREAD

**Issue by rohit7209** [electron-userland/electron-packager#651]
I am using 
windows 10
nodejs version: 6.10.3
electron version: 1.6.8

while rebuilding electron after installing 'modbus-serial' i am getting below error...

× Rebuild Failed
An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.1
gyp info using node@6.10.3 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'c:\\ecube\\app\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\ecube\\app\\node_modules\\serialport\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\ecube\\app\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\rohit\\.electron-gyp\\.node-gyp\\iojs-1.6.8\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\rohit\\.electron-gyp\\.node-gyp\\iojs-1.6.8',
gyp info spawn args   '-Dnode_gyp_dir=c:\\ecube\\app\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=c:\\ecube\\app\\node_modules\\serialport',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'c:\\ecube\\app\\node_modules\\serialport\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
VCBUILD : error : project file 'c:\ecube\app\node_modules\serialport\build\serialport.vcproj' was not found or not a valid project file. [c:\ecube\app\node_modules\serialport\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\ecube\app\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\ecube\\app\\node.exe" "c:\\ecube\\app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.6.8" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=serialport" "--module_path=c:\\ecube\\app\\node_modules\\serialport\\build\\Release" "--host=https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7"
gyp ERR! cwd c:\ecube\app\node_modules\serialport
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.1
gyp info using node@6.10.3 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'c:\\ecube\\app\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\ecube\\app\\node_modules\\serialport\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\ecube\\app\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\rohit\\.electron-gyp\\.node-gyp\\iojs-1.6.8\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\rohit\\.electron-gyp\\.node-gyp\\iojs-1.6.8',
gyp info spawn args   '-Dnode_gyp_dir=c:\\ecube\\app\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=c:\\ecube\\app\\node_modules\\serialport',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'c:\\ecube\\app\\node_modules\\serialport\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
VCBUILD : error : project file 'c:\ecube\app\node_modules\serialport\build\serialport.vcproj' was not found or not a valid project file. [c:\ecube\app\node_modules\serialport\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\ecube\app\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\ecube\\app\\node.exe" "c:\\ecube\\app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.6.8" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=serialport" "--module_path=c:\\ecube\\app\\node_modules\\serialport\\build\\Release" "--host=https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7"
gyp ERR! cwd c:\ecube\app\node_modules\serialport
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (c:\ecube\app\node_modules\spawn-rx\lib\src\index.js:262:84)
    at SafeSubscriber.__tryOrUnsub (c:\ecube\app\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.error (c:\ecube\app\node_modules\rxjs\Subscriber.js:197:26)
    at Subscriber._error (c:\ecube\app\node_modules\rxjs\Subscriber.js:128:26)
    at Subscriber.error (c:\ecube\app\node_modules\rxjs\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (c:\ecube\app\node_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (c:\ecube\app\node_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber._next (c:\ecube\app\node_modules\spawn-rx\lib\src\index.js:236:65)
    at SafeSubscriber.__tryOrUnsub (c:\ecube\app\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.next (c:\ecube\app\node_modules\rxjs\Subscriber.js:185:22)

**Comment by AdamMikacich** [comment]
What was your solution?

**Comment by malept** [comment]
Use electron-rebuild, or Electron Forge (which uses both Packager and electron-rebuild under the hood).

**Comment by AdamMikacich** [comment]
I am using electron-rebuild. I am getting a similar error to above. Here is my log: https://pastebin.com/B6WjDEXP However, I believe my issue is being caused by node serialport. Do you have any idea for a solution?

**Comment by malept** [comment]
You're better off asking in one of the [Electron community forums](https://github.com/electron/electron#community). electron-rebuild is outside the scope of this project.
