### ISSUE TITLE
packager(options) == undefined

### ISSUE THREAD

**Issue by dmos62** [electron-userland/electron-packager#689]
* [x ] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

When running this small electron-packager api script, `packager(options)` call returns `undefined`. When using the CLI interface, everything works. I'm trying to use the programmatic api, because that way the routine is easier to maintain, and you can write a predicate function for ignoring files.

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
>  env DEBUG=\* node package.win.js
Mon, 24 Jul 2017 13:29:15 GMT electron-packager Electron Packager 8.7.2
Mon, 24 Jul 2017 13:29:15 GMT electron-packager Node v8.1.2
Mon, 24 Jul 2017 13:29:15 GMT electron-packager Host Operating system: win32 (x64)
Mon, 24 Jul 2017 13:29:15 GMT electron-packager Packager Options: {"dir":"."}
Mon, 24 Jul 2017 13:29:15 GMT electron-packager Target Platforms: win32
Mon, 24 Jul 2017 13:29:15 GMT electron-packager Target Architectures: x64
Mon, 24 Jul 2017 13:29:15 GMT get-package-info Getting props:  [ [ 'productName', 'name' ],
  'version',
  [ 'dependencies.electron',
    'devDependencies.electron',
    'dependencies.electron-prebuilt-compile',
    'devDependencies.electron-prebuilt-compile',
    'dependencies.electron-prebuilt',
    'devDependencies.electron-prebuilt' ] ]
Mon, 24 Jul 2017 13:29:15 GMT get-package-info Looking up starting from directory:  E:\ivairus\cygwin\home\Dominykas\darbalaukiai\__kontraktai\iko-app
Mon, 24 Jul 2017 13:29:15 GMT get-package-info Result so far: { values: {}, source: {} }
E:\ivairus\cygwin\home\Dominykas\darbalaukiai\__kontraktai\iko-app\package.win.js:18
  .then((appPaths) => {
  ^

TypeError: Cannot read property 'then' of undefined
    at Object.<anonymous> (E:\ivairus\cygwin\home\Dominykas\darbalaukiai\__kontr
aktai\iko-app\package.win.js:18:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

`package.win.js`:
```
const packager = require('electron-packager')
const options = {
  dir: '.'
}

packager(options)
  .then((appPaths) => {
    console.log('done!!!')
  })
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

`package.json`:
```
{
  "name": "app",
  "version": "1.0.0",
  "description": "x",
  "author": "x",
  "dependencies": {
    "@angular/animations": "^4.3.1",
    "@angular/common": "^4.3.1",
    "@angular/compiler": "^4.3.1",
    "@angular/core": "^4.3.1",
    "@angular/forms": "^4.3.1",
    "@angular/http": "^4.3.1",
    "@angular/platform-browser": "^4.3.1",
    "@angular/platform-browser-dynamic": "^4.3.1",
    "@angular/platform-server": "^4.3.1",
    "@angular/router": "^4.3.1",
    "@angularclass/conventions-loader": "^1.0.13",
    "@angularclass/hmr": "~1.2.2",
    "@angularclass/hmr-loader": "^3.0.4",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.28",
    "body-parser": "^1.17.2",
    "bootstrap": "^4.0.0-alpha.6",
    "core-js": "^2.4.1",
    "electron-squirrel-startup": "^1.0.0",
    "epub.js": "^0.2.15",
    "express": "^4.15.3",
    "ie-shim": "^0.1.0",
    "jszip": "^2.6.1",
    "pace-progress": "^1.0.2",
    "pdfjs-dist": "^1.8.562",
    "preboot": "^4.5.2",
    "ramda": "^0.24.1",
    "reflect-metadata": "^0.1.10",
    "rxjs": "5.4.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^4.3.1",
    "@types/hammerjs": "^2.0.34",
    "@types/jasmine": "2.5.53",
    "@types/node": "^7.0.38",
    "@types/source-map": "^0.5.0",
    "@types/uglify-js": "^2.6.28",
    "@types/webpack": "^2.2.15",
    "add-asset-html-webpack-plugin": "^2.0.1",
    "angular2-template-loader": "^0.6.2",
    "assets-webpack-plugin": "^3.5.1",
    "awesome-typescript-loader": "~3.1.3",
    "codelyzer": "^3.1.2",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.4",
    "electron": "^1.7.5",
    "electron-packager": "^8.7.2",
    "electron-winstaller": "^2.6.3",
    "exports-loader": "^0.6.4",
    "expose-loader": "^0.7.3",
    "extract-text-webpack-plugin": "~2.1.0",
    "file-loader": "^0.11.1",
    "find-root": "^1.1.0",
    "gh-pages": "^1.0.0",
    "html-webpack-plugin": "^2.29.0",
    "http-server": "^0.10.0",
    "imports-loader": "^0.7.1",
    "jasmine-core": "^2.6.2",
    "json-loader": "^0.5.6",
    "karma": "^1.7.0",
    "karma-jasmine": "^1.1.0",
    "karma-mocha-reporter": "^2.2.3",
    "karma-sourcemap-loader": "~0.3",
    "karma-webpack": "^2.0.4",
    "ng-router-loader": "^2.1.0",
    "ngc-webpack": "~2.0.0",
    "node-pre-gyp": "^0.6.36",
    "node-sass": "^4.5.3",
    "npm-run-all": "^4.0.2",
    "optimize-js-plugin": "0.0.4",
    "parse5": "^3.0.2",
    "protractor": "^5.1.2",
    "raw-loader": "0.5.1",
    "resolve-url-loader": "^2.1.0",
    "rimraf": "~2.6.1",
    "sass-loader": "^6.0.5",
    "script-ext-html-webpack-plugin": "^1.8.5",
    "source-map-loader": "^0.2.1",
    "string-replace-loader": "~1.2.0",
    "style-loader": "^0.18.1",
    "to-string-loader": "^1.1.5",
    "ts-node": "^3.2.1",
    "tslib": "^1.7.1",
    "tslint": "~5.4.2",
    "tslint-loader": "^3.5.3",
    "typedoc": "^0.7.1",
    "typescript": "~2.3.2",
    "url-loader": "^0.5.8",
    "webpack": "~2.5.1",
    "webpack-dev-middleware": "^1.11.0",
    "webpack-dev-server": "^2.6.0",
    "webpack-dll-bundles-plugin": "^1.0.0-beta.5",
    "webpack-merge": "~4.1.0"
  },
  "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 3"
  }
}
```

**Comment by MarshallOfSound** [comment]
> Please describe your issue:

You missed this bit out, not sure what your actual issue is here

**Comment by dmos62** [comment]
@MarshallOfSound I did. I edited somewhat. In that section I wrote:

> When running this small electron-packager api script, packager(options) call returns undefined.

That is just a verbalisation of the short `DEBUG=*` run though.

**Comment by MarshallOfSound** [comment]
@dmos62 The promise PR was merged after the latest release.  I.e. The promise return value has not been released yet.

You'll need to wait for the next packager release
