### ISSUE TITLE
linux packaging failed

### ISSUE THREAD

**Issue by JyotirmoyGoswami** [electron-userland/electron-packager#692]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Put the console output here

0 info it worked if it ends with ok
1 verbose cli [ '/home/jyotirmoy/Softwares/NODE/bin/node',
1 verbose cli   '/home/jyotirmoy/Softwares/NODE/bin/npm',
1 verbose cli   'run',
1 verbose cli   'pack' ]
2 info using npm@5.3.0
3 info using node@v8.1.3
4 verbose run-script [ 'prepack', 'pack', 'postpack' ]
5 info lifecycle demo@1.0.0~prepack: demo@1.0.0
6 info lifecycle demo@1.0.0~pack: demo@1.0.0
7 verbose lifecycle demo@1.0.0~pack: unsafe-perm in lifecycle true
8 verbose lifecycle demo@1.0.0~pack: PATH: /home/jyotirmoy/Softwares/NODE/lib/node_modules/npm/bin/node-gyp-bin:/home/jyotirmoy/Workspace/desktop/demo/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/jyotirmoy/Softwares/ANDROID/platform-tools:/home/jyotirmoy/Softwares/JAVA:/home/jyotirmoy/Softwares/JAVA/jre:/home/jyotirmoy/Softwares/JAVA/bin:/home/jyotirmoy/Softwares/JAVA/lib:/home/jyotirmoy/Softwares/ANT:/home/jyotirmoy/Softwares/ANT/bin:/home/jyotirmoy/Softwares/ANDROID:/home/jyotirmoy/Softwares/ANDROID/tools:/home/jyotirmoy/Softwares/ANDROID/platforms:/home/jyotirmoy/Softwares/ANDROID/platform-tools:/home/jyotirmoy/Softwares/ANDROID/build-tools:/home/jyotirmoy/Softwares/NODE/bin:/home/jyotirmoy/Softwares/MONGODB/bin:/home/jyotirmoy/Softwares/arduino-1.8.0:/home/jyotirmoy/Softwares/ANDROID/platform-tools:/home/jyotirmoy/Softwares/JAVA:/home/jyotirmoy/Softwares/JAVA/jre:/home/jyotirmoy/Softwares/JAVA/bin:/home/jyotirmoy/Softwares/JAVA/lib:/home/jyotirmoy/Softwares/ANT:/home/jyotirmoy/Softwares/ANT/bin:/home/jyotirmoy/Softwares/ANDROID:/home/jyotirmoy/Softwares/ANDROID/tools:/home/jyotirmoy/Softwares/ANDROID/platforms:/home/jyotirmoy/Softwares/ANDROID/platform-tools:/home/jyotirmoy/Softwares/ANDROID/build-tools:/home/jyotirmoy/Softwares/NODE/bin:/home/jyotirmoy/Softwares/MONGODB/bin:/home/jyotirmoy/Softwares/arduino-1.8.0
9 verbose lifecycle demo@1.0.0~pack: CWD: /home/jyotirmoy/Workspace/desktop/demo
10 silly lifecycle demo@1.0.0~pack: Args: [ '-c',
10 silly lifecycle   'electron-packager . demo --out=dist --arch=x64 --platform=linux --electron-version=1.0.0 --overwrite --prune --ignore=dist' ]
11 silly lifecycle demo@1.0.0~pack: Returned: code: 1  signal: null
12 info lifecycle demo@1.0.0~pack: Failed to exec pack script
13 verbose stack Error: demo@1.0.0 pack: `electron-packager . demo --out=dist --arch=x64 --platform=linux --electron-version=1.0.0 --overwrite --prune --ignore=dist`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/jyotirmoy/Softwares/NODE/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/jyotirmoy/Softwares/NODE/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:897:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
14 verbose pkgid demo@1.0.0
15 verbose cwd /home/jyotirmoy/Workspace/desktop/demo
16 verbose Linux 4.4.0-83-generic
17 verbose argv "/home/jyotirmoy/Softwares/NODE/bin/node" "/home/jyotirmoy/Softwares/NODE/bin/npm" "run" "pack"
18 verbose node v8.1.3
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error demo@1.0.0 pack: `electron-packager . demo --out=dist --arch=x64 --platform=linux --electron-version=1.0.0 --overwrite --prune --ignore=dist`
22 error Exit status 1
23 error Failed at the demo@1.0.0 pack script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**
electron-packager . demo --out=dist --arch=x64 --platform=linux --electron-version=1.0.0 --overwrite --prune --ignore=dist
Put the arguments or parameters here
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists. *Make sure to run the `electron-packager` command without using `npm run` and make a note of the output, because `npm run` does not print out error messages when a script errors.*

Please note that:

* You're specifying `--electron-version=1.0.0`, which is a very old version.
* You're using NPM 5.3.0, which has [known issues with pruning](https://github.com/npm/npm/issues/17781). Please try NPM 5.1.x or 5.2.x.

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
