### ISSUE TITLE
win32metadata.CompanyName inferring does not work when package.json author is an object

### ISSUE THREAD

**Issue by naderm** [electron-userland/electron-packager#718]
Re-filing https://github.com/electron-userland/electron-forge/issues/311 here

Hi,

Running electron-forge make generates the following error when using a dict for the author portion of package.json:

```
// package.json:
"author": {
"name" : "Barney Rubble",
"email" : "b@rubble.com",
"url" : "http://barnyrubble.tumblr.com/"
}
--- 
$ electron-forge --version
‼ You are using Yarn, but not a known good version.
The known versions that work with Electron Forge are: 0.23.3 || 0.24.6
√ Checking your system
4.0.0
$ electron-forge make
‼ You are using Yarn, but not a known good version.
The known versions that work with Electron Forge are: 0.23.3 || 0.24.6
√ Checking your system
√ Resolving Forge Config
We need to package your application before we can make it
An unhandled exception has occurred inside Forge:
expected author to be a string
TypeError: expected author to be a string
    at module.exports (C:\projects\camv\node_modules\parse-author\index.js:14:11)
    at getPackageInfo (C:\projects\camv\node_modules\electron-packager\infer.js:124:40)
    at tryCatcher (C:\projects\camv\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\projects\camv\node_modules\bluebird\js\release\nodeify.js:23:30)
    at Promise._settlePromise (C:\projects\camv\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\projects\camv\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\projects\camv\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\projects\camv\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\projects\camv\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\projects\camv\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

However using the alternative author format does not generate this error:

```
// package.json:
"Barney Rubble <b@rubble.com> (http://barnyrubble.tumblr.com/)"
---
$ electron-forge --version
‼ You are using Yarn, but not a known good version.
The known versions that work with Electron Forge are: 0.23.3 || 0.24.6
√ Checking your system
4.0.0
$ electron-forge make
‼ You are using Yarn, but not a known good version.
The known versions that work with Electron Forge are: 0.23.3 || 0.24.6
√ Checking your system
√ Resolving Forge Config
We need to package your application before we can make it
√ Preparing to Package Application for arch: x64
√ Compiling Application
√ Preparing native dependencies: 1 / 1
√ Packaging Application
...
```

**Comment by malept** [comment]
Fix released in 9.0.1.
