### ISSUE TITLE
Fatal error: Unable to set icon

### ISSUE THREAD

**Issue by B-ot** [electron-userland/electron-packager#803]
Im trying to build an electron app into a single exe on windows. Im passing this command: yarn dist
and get this error:

Error: Exit code: 1. Command failed: C:\Users\user\AppData\Local\electron-builder\cache\winCodeSign\winCodeSign-1.9.0\rcedit.exe C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\dist\win-ia32-unpacked\AdiBotGUI.exe --set-version-string FileDescription AdiBotGUI --set-version-string ProductName AdiBotGUI --set-version-string LegalCopyright Copyright © 2018 AdiBot --set-file-version 1.0.0 --set-product-version 1.0.0.0 --set-version-string InternalName AdiBotGUI --set-version-string OriginalFilename  --set-version-string CompanyName AdiBot --set-icon C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\build\icon.ico
Fatal error: Unable to set icon

Fatal error: Unable to set icon

    at C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\builder-util\src\util.ts:122:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at exec (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\builder-util\src\util.ts:85:3)
    at execWine (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\builder-util\src\wine.ts:60:12)
    at C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder-lib\src\winPackager.ts:327:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.signAndEditResources (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder-lib\out\winPackager.js:411:11)
    at C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder-lib\src\winPackager.ts:344:18
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder-lib\out\winPackager.js:429:11)
    at C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder-lib\src\platformPackager.ts:214:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.doPack (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder-lib\out\platformPackager.js:284:11)
    at C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder-lib\src\platformPackager.ts:114:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder-lib\out\platformPackager.js:202:11)
    at C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder-lib\src\packager.ts:364:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder-lib\out\packager.js:432:11)
    at C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder-lib\src\packager.ts:308:52
    at Generator.next (<anonymous>)
    at C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder-lib\out\packager.js:376:11)
    at C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder-lib\src\packager.ts:270:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder-lib\out\packager.js:332:11)
    at C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder\src\builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder\out\builder.js:61:21)
    at build (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder\src\builder.ts:280:10)
    at then (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at Object.runCommand (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\yargs\yargs.js:1042:24)
    at Object.get [as argv] (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\Users\user\adibot1.1\Adi_botGUI\Adi_botGUI\node_modules\electron-builder\src\cli\cli.ts:42:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

I have tried adding my own icon but that returns the same error.

**Comment by malept** [comment]
This will be fixed when a new version of node-rcedit is released.

Also, you're using electron-builder, not Electron Packager.

**Comment by RockGuitarist1** [comment]
Was this node-rcedit fix included in the 11.0.1 update? I still seem to be getting this issue. I saw this, but didn't know if it was included:

`rcedit module updated to 1.0.0, which fixes some bugs (#804)`

**Comment by malept** [comment]
That's my understanding. If it's not, please file a bug in the node-rcedit issue tracker rather than here.

**Comment by RockGuitarist1** [comment]
This has been fixed in their update. Those who are having this issue, make sure you are trying to set an `.ico` and using this format: `electron-packager . Electron-App --icon=src/assets/images/icon.ico`.

**Comment by malept** [comment]
FYI, the file extension is optional. It's derived from the target platform.
