### ISSUE TITLE
"Unable to find a valid app" error when trying to package webpack build

### ISSUE THREAD

**Issue by lukejagodzinski** [electron-userland/electron-packager#834]
After building app for MacOS and running app I get the following error:

```
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/Users/lukejagodzinski/workspace/node/rename/release-builds/Rename-darwin-x64/Rename.app/Contents/Resources/electron.asar/browser/init.js:121:9)
    at Object.<anonymous> (/Users/lukejagodzinski/workspace/node/rename/release-builds/Rename-darwin-x64/Rename.app/Contents/Resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
```

What I'm doing is first building app with webpack and trying to package such an app but without success.

Here is my `package.json` file:

```json
{
  "name": "rename",
  "productName": "Rename",
  "version": "1.0.0",
  "main": "./dist/main.js",
  "scripts": {
    "build": "concurrently \"npm run build-main\" \"npm run build-renderer\"",
    "build-main": "node -r @babel/register ./node_modules/.bin/webpack --config ./config/main.production.js",
    "build-renderer": "node -r @babel/register ./node_modules/.bin/webpack --config ./config/renderer.production.js",
    "build-mac": "electron-packager ./dist/ --overwrite --platform=darwin --arch=x64 --icon=assets/icons/mac/icon.icns --prune=true --out=release-builds",
    "create-icon": "electron-icon-maker --input=./assets/icon.png --output=./assets",
    "start": "electron ./dist/main.js"
  },
  "author": "Łukasz Jagodziński <luke.jagodzinski@gmail.com>",
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.46",
    "@babel/plugin-proposal-class-properties": "^7.0.0-beta.46",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0-beta.46",
    "@babel/plugin-transform-runtime": "^7.0.0-beta.46",
    "@babel/preset-env": "^7.0.0-beta.46",
    "@babel/preset-react": "^7.0.0-beta.46",
    "@babel/register": "^7.0.0-beta.46",
    "babel-loader": "^8.0.0-beta.0",
    "concurrently": "^3.5.1",
    "copy-webpack-plugin": "^4.5.1",
    "cross-env": "^5.1.4",
    "electron": "^1.8.6",
    "electron-icon-maker": "0.0.4",
    "electron-packager": "^12.0.1",
    "html-webpack-plugin": "^3.2.0",
    "webpack": "^4.6.0",
    "webpack-cli": "^2.0.15",
    "webpack-merge": "^4.1.2"
  },
  "dependencies": {
    "@babel/runtime": "^7.0.0-beta.46",
    "electron-store": "^1.3.0",
    "exif-reader": "^1.0.2",
    "lodash": "^4.17.10",
    "material-ui": "^1.0.0-beta.43",
    "material-ui-icons": "^1.0.0-beta.36",
    "moment": "^2.22.1",
    "prop-types": "^15.6.1",
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0"
  }
}
```

As you can see I'm using webpack, and the build files are put in the `./dist/` directory.

What am I doing wrong?

**Comment by lukejagodzinski** [comment]
I solved my problem. In the `dist` directory there need to be `package.json` file too.

**Comment by crane168** [comment]
Hello, I have the same problem with you, but there is package. Json in my dist directory, error is still reported。

**Comment by crane168** [comment]
@lukejagodzinski  Hello, I have the same problem with you, but there is package. Json in my dist directory, error is still reported.

**Comment by schwiet** [comment]
I had the same issue too and I had a `package.json` present. Running:
`electron-packager ./dist --out=./dist/` would result in no `app/` in the package (i.e. my app was silently not being packaged). If I instead first changed into `./dist`, all is well again:

```
cd dist
electron-packager .
```
