### ISSUE TITLE
The ordinal 345 could not be located in the dynamic link library

### ISSUE THREAD

**Issue by vaidyaanand** [electron-userland/electron-packager#860]
I am trying to install .exe file in windows system. But unable to do it and getting **"The ordinal 345 could not be located in the dynamic link library"** error. 
My Command is:
`"electron-packager . myApp --overwrite --asar=true --platform=win32 --arch=x64 --icon=iconnewa1.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName=' myApp'"`

I am getting following error in some windows system and unable to solve it 
Error log file:
```
2018-01-17 15:39:56> Program: Starting Squirrel Updater: --install .
2018-01-17 15:39:56> Program: Starting install, writing to C:\Users\user1\AppData\Local\SquirrelTemp
2018-01-17 15:39:56> Program: About to install to: C:\Users\user1\AppData\Local\myApp
2018-01-17 15:39:56> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user1\AppData\Local\myApp\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2018-01-17 15:39:56> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user1\AppData\Local\myApp\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2018-01-17 15:39:56> CheckForUpdateImpl: Reading RELEASES file from C:\Users\user1\AppData\Local\SquirrelTemp
2018-01-17 15:39:56> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2018-01-17 15:39:56> ApplyReleasesImpl: Writing files to app directory: C:\Users\user1\AppData\Local\myApp\app-5.1.1
2018-01-17 15:40:00> LogHost: Rigging execution stub for MyApp_ExecutionStub.exe to C:\Users\user1\AppData\Local\myApp\MyApp.exe
2018-01-17 15:40:02> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\user1\AppData\Local\myApp\app-5.1.1\MyApp.exe]
2018-01-17 15:40:08> ApplyReleasesImpl: Starting fixPinnedExecutables
2018-01-17 15:40:08> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2018-01-17 15:40:08> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2018-01-17 15:40:08> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2018-01-17 15:40:08> ApplyReleasesImpl: Examining Pin: Outlook 2016.lnk
2018-01-17 15:40:08> ApplyReleasesImpl: Examining Pin: Skype for Business 2016.lnk
2018-01-17 15:40:08> ApplyReleasesImpl: Fixing up tray icons
2018-01-17 15:40:08> ApplyReleasesImpl: cleanDeadVersions: for version 5.1.1
2018-01-17 15:40:08> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-5.1.1
2018-02-19 16:33:12> Program: Starting Squirrel Updater: --install .
2018-02-19 16:33:12> Program: Starting install, writing to C:\Users\user1\AppData\Local\SquirrelTemp
2018-02-19 16:33:12> Program: About to install to: C:\Users\user1\AppData\Local\myApp
2018-02-19 16:33:12> Program: Install path C:\Users\user1\AppData\Local\myApp already exists, burning it to the ground
2018-02-19 16:33:13> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user1\AppData\Local\myApp\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2018-02-19 16:33:13> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user1\AppData\Local\myApp\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2018-02-19 16:33:13> CheckForUpdateImpl: Reading RELEASES file from C:\Users\user1\AppData\Local\SquirrelTemp
2018-02-19 16:33:13> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2018-02-19 16:33:13> ApplyReleasesImpl: Writing files to app directory: C:\Users\user1\AppData\Local\myApp\app-6.2.5
2018-02-19 16:33:16> LogHost: Rigging execution stub for MyApp_ExecutionStub.exe to C:\Users\user1\AppData\Local\myApp\MyApp.exe
2018-02-19 16:33:17> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\user1\AppData\Local\myApp\app-6.2.5\MyApp.exe]
2018-02-19 16:33:22> ApplyReleasesImpl: Starting fixPinnedExecutables
2018-02-19 16:33:22> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2018-02-19 16:33:22> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2018-02-19 16:33:22> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2018-02-19 16:33:22> ApplyReleasesImpl: Examining Pin: Outlook 2016.lnk
2018-02-19 16:33:22> ApplyReleasesImpl: Examining Pin: Skype for Business 2016.lnk
2018-02-19 16:33:22> ApplyReleasesImpl: Fixing up tray icons
2018-02-19 16:33:22> ApplyReleasesImpl: cleanDeadVersions: for version 6.2.5
2018-02-19 16:33:22> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-6.2.5
2018-03-21 09:50:52> Program: Starting Squirrel Updater: --install . -s --rerunningWithoutUAC
2018-03-21 09:50:52> Program: Starting install, writing to C:\Users\user1\AppData\Local\SquirrelTemp
2018-03-21 09:50:52> UpdateManager: using rootAppDirecotry: C:\Users\user1\AppData\Local\Microsoft\Teams
2018-03-21 09:50:52> Program: About to install to: C:\Users\user1\AppData\Local\Microsoft\Teams
2018-03-21 09:50:52> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user1\AppData\Local\Microsoft\Teams\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2018-03-21 09:50:52> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user1\AppData\Local\Microsoft\Teams\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__43.MoveNext()
2018-03-21 09:50:52> CheckForUpdateImpl: Reading RELEASES file from C:\Users\user1\AppData\Local\SquirrelTemp
2018-03-21 09:50:52> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2018-03-21 09:50:53> ApplyReleasesImpl: getting squirrel aware apps failed with exception Could not find a part of the path 'C:\Users\user1\AppData\Local\Microsoft\Teams\current'.
2018-03-21 09:50:53> ApplyReleasesImpl: Writing files to app directory: C:\Users\user1\AppData\Local\Microsoft\Teams\current
2018-03-21 09:50:55> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\user1\AppData\Local\Microsoft\Teams\current\Teams.exe]
2018-03-21 09:50:59> ApplyReleasesImpl: Starting fixPinnedExecutables
2018-03-21 09:50:59> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2018-03-21 09:50:59> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2018-03-21 09:50:59> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2018-03-21 09:50:59> ApplyReleasesImpl: Examining Pin: Outlook 2016.lnk
2018-03-21 09:50:59> ApplyReleasesImpl: Examining Pin: Skype for Business 2016.lnk
2018-03-21 09:50:59> ApplyReleasesImpl: Fixing up tray icons
2018-03-21 09:50:59> MeetingAddinInstaller: System.ArgumentException: Cannot delete a subkey tree because the subkey does not exist.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey)
   at Squirrel.MeetingAddinInstaller.<InstallMeetingAddinAsync>d__3.MoveNext()
2018-03-21 09:50:59> MeetingAddinInstaller: Version: 1.0.17192.2; addinPackageDirectory: 1.0.17192.2
2018-03-21 09:50:59> MeetingAddinInstaller: Creating local meeting add-in folder TeamsMeetingAddin
2018-03-21 09:50:59> MeetingAddinInstaller: .dead exists: False
2018-03-21 09:50:59> MeetingAddinInstaller: path to .dead: C:\Users\user1\AppData\Local\Microsoft\TeamsMeetingAddin\1.0.17192.2\.dead
2018-03-21 09:50:59> MeetingAddinInstaller: before cleanup unused versions
2018-03-21 09:51:00> MeetingAddinInstaller: Version 1.0.17192.2 of the meeting add-in is now installed
2018-03-21 09:51:00> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.00.22051
2018-03-21 09:51:00> ApplyReleasesImpl: cleanDeadVersions: exclude folder stage
2018-05-02 15:24:05> Program: Starting Squirrel Updater: --install .
2018-05-02 15:24:05> Program: Starting install, writing to C:\Users\user1\AppData\Local\SquirrelTemp
2018-05-02 15:24:05> Program: About to install to: C:\Users\user1\AppData\Local\myApp
2018-05-02 15:24:05> Program: Install path C:\Users\user1\AppData\Local\myApp already exists, burning it to the ground
2018-05-02 15:24:07> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user1\AppData\Local\myApp\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2018-05-02 15:24:07> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user1\AppData\Local\myApp\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2018-05-02 15:24:07> CheckForUpdateImpl: Reading RELEASES file from C:\Users\user1\AppData\Local\SquirrelTemp
2018-05-02 15:24:07> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2018-05-02 15:24:07> ApplyReleasesImpl: Writing files to app directory: C:\Users\user1\AppData\Local\myApp\app-8.2.0
2018-05-02 15:24:11> LogHost: Rigging execution stub for MyApp_ExecutionStub.exe to C:\Users\user1\AppData\Local\myApp\MyApp.exe
2018-05-02 15:24:13> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\user1\AppData\Local\myApp\app-8.2.0\MyApp.exe]
2018-05-02 15:24:18> ApplyReleasesImpl: Starting fixPinnedExecutables
2018-05-02 15:24:18> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2018-05-02 15:24:18> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2018-05-02 15:24:18> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2018-05-02 15:24:18> ApplyReleasesImpl: Examining Pin: Outlook 2016.lnk
2018-05-02 15:24:18> ApplyReleasesImpl: Examining Pin: Skype for Business 2016.lnk
2018-05-02 15:24:18> ApplyReleasesImpl: Fixing up tray icons
2018-05-02 15:24:18> ApplyReleasesImpl: cleanDeadVersions: for version 8.2.0
2018-05-02 15:24:18> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-8.2.0

```

* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
Put the console output here
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
Put the arguments or parameters here
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

**Comment by malept** [comment]
I don't think this is a bug in Electron Packager. If you search for this error elsewhere, you get https://github.com/Microsoft/vscode/issues/25577, and I think VSCode has its own build system that they use to bundle their app instead of Packager. Unfortunately since I'm not particularly familiar with that error, I don't know where you'd go to investigate it in more depth.

**Comment by vaidyaanand** [comment]
[https://github.com/electron-userland/electron-builder/issues/552](url)
Please check above URL. As asar is true in my case, it is something related to the electron-packager itself. I have searched a lot. There is no tutorial for it in your plugin.

**Comment by MarshallOfSound** [comment]
@vaidyaanand The error log you posted comes from nothing to do with `electron-packager`, without conclusive proof that this is a packager issue this appears to be an issue with some other dependency in your build / installation logic.

**Comment by MarshallOfSound** [comment]
@vaidyaanand You literally posted a `Squirrel.Windows` error log, zero ways to reproduce on the `electron-packager` issue tracker without even filling in the issue template completely.  Open source is not free support, we provide this package and help people out where we can.  You seem to be under the misimpression that you are somehow entitled to support and that switching packagers will somehow make us come back begging to help you.

It won't

I do hope that you solve your issue and that in the future you communicate with open source projects in a nicer more mutually respectful way
