### ISSUE TITLE
ENOENT: no such file or directory, lstat

### ISSUE THREAD

**Issue by diogo-raphael-cravo** [electron-userland/electron-packager#895]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**

**Console output when you run electron-packager with the environment variable `DEBUG=electron-packager`. Please include the stack trace if one exists.**

```
PS E:\project\teste\electron-quick-start> node ./build.js
  electron-packager Electron Packager 12.1.2
  electron-packager Node v8.9.3
  electron-packager Host Operating system: win32 (x64) +0ms
  electron-packager Packager Options: {"asar":{},"tmpdir":"C:\\Users\\LOCALU~1\\AppData\\Local\\Temp","dir":"./","overwrite":true,"out":"./dist"} +0ms
  electron-packager Target Platforms: win32 +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring application name from name in E:\project\teste\electron-quick-start\package.json +0ms
  electron-packager Inferring appVersion from version in E:\project\teste\electron-quick-start\package.json +0ms
  electron-packager Inferring win32metadata.CompanyName from author in E:\project\teste\electron-quick-start\package.json +0ms
  electron-packager Inferring target Electron version from electron in E:\project\teste\electron-quick-start\package.json +19ms
  electron-packager Application name: electron-quick-start +20ms
  electron-packager Target Electron version: 3.0.0 +0ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)', '/node_modules/\\.bin($|/)', '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"platform":"win32","arch":"x64","version":"3.0.0"} +0ms
Packaging app for platform win32 x64 using electron v3.0.0
  electron-packager Creating C:\Users\LOCALU~1\AppData\Local\Temp\electron-packager\win32-x64-template +355ms
  electron-packager Extracting C:\Users\LocalUser\AppData\Local\electron\Cache\electron-v3.0.0-win32-x64.zip to C:\Users\LOCALU~1\AppData\Local\Temp\electron-packager\win32-x64-template +0ms
  electron-packager Initializing app in C:\Users\LOCALU~1\AppData\Local\Temp\electron-packager\win32-x64\electron-quick-start-win32-x64 from C:\Users\LOCALU~1\AppData\Local\Temp\electron-packager\win32-x64-template template +0ms  electron-packager Ignored paths based on the out param: [ 'E:\\project\\teste\\electron-quick-start\\dist' ] +4s
  electron-packager Running asar with the options {} +9s
fs.js:941
  binding.lstat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, lstat 'C:\Users\LOCALU~1\AppData\Local\Temp\electron-packager\win32-x64\electron-quick-start-win32-x64\resources\app\C:\Users\LOCALU~1\AppData\Local\Temp\electron-packager\win32-x64\electron-quick-start-win32-x64\resources\app\.gitignore'
    at Object.fs.lstatSync (fs.js:941:11)
    at handleFile (E:\project\teste\electron-quick-start\node_modules\asar\lib\asar.js:116:23)
    at next (E:\project\teste\electron-quick-start\node_modules\asar\lib\asar.js:170:12)
    at Object.module.exports.createPackageFromFiles (E:\project\teste\electron-quick-start\node_modules\asar\lib\asar.js:175:10)
    at E:\project\teste\electron-quick-start\node_modules\asar\lib\asar.js:50:20
    at E:\project\teste\electron-quick-start\node_modules\asar\lib\crawlfs.js:19:12
    at f (E:\project\teste\electron-quick-start\node_modules\once\once.js:25:25)
    at Glob.<anonymous> (E:\project\teste\electron-quick-start\node_modules\glob\glob.js:146:7)
    at emitOne (events.js:116:13)
    at Glob.emit (events.js:211:7)
    at Glob._finish (E:\project\teste\electron-quick-start\node_modules\glob\glob.js:185:8)
    at done (E:\project\teste\electron-quick-start\node_modules\glob\glob.js:172:12)
    at Glob._processGlobStar2 (E:\project\teste\electron-quick-start\node_modules\glob\glob.js:614:12)
    at E:\project\teste\electron-quick-start\node_modules\glob\glob.js:603:10
    at RES (E:\project\teste\electron-quick-start\node_modules\inflight\inflight.js:31:16)
    at f (E:\project\teste\electron-quick-start\node_modules\once\once.js:25:25)
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `packager()` function?**

```
require('electron-packager')({
	asar: { },
	tmpdir: require('os').tmpdir(),
	dir: './',
	overwrite: true,
	out: './dist',
});
```

**Please provide either a failing minimal testcase (with a link to the code) or detailed steps to
reproduce your problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start)
is a good starting point.**

On Windows 10:
```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install electron-packager@12.1.2
```

Now create a file called build.js with following contents:
```
require('electron-packager')({
	asar: { },
	tmpdir: require('os').tmpdir(),
	dir: './',
	overwrite: true,
	out: './dist',
});
```

And finally run `node ./build.js`.

**Expected output:**
The app is packaged as usual.

**Actual output:**
The error message pasted above.

**I've tried installing asar@0.14.3 and it works. I think it might have something to do with asar@0.14.4.**

Thank you in advance for your help!

**Comment by diogo-raphael-cravo** [comment]
Just found a similar issue, sorry: https://github.com/electron-userland/electron-packager/issues/892

**Comment by bemous** [comment]
Hi very body,
i have the same error trying to install asar with **npm install -g asar** or **npm i -g asar** and have this error **Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:129:28)** 
I use macOS BigSur, can any body help me?

Thanks

**Comment by malept** [comment]
@bemous this sounds like a Node.js/npm issue, not am Electron Packager (or asar) issue. I recommend you follow up on one of those communities.

**Comment by bemous** [comment]
@malept took thanks.
