### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by infin1tyy** [electron-userland/electron-packager#996]
I have an issue while building with `package-win`.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'package-win' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prepackage-win', 'package-win', 'postpackage-win' ]
5 info lifecycle discord-rpc-tool@1.0.0~prepackage-win: discord-rpc-tool@1.0.0
6 info lifecycle discord-rpc-tool@1.0.0~package-win: discord-rpc-tool@1.0.0
7 verbose lifecycle discord-rpc-tool@1.0.0~package-win: unsafe-perm in lifecycle true
8 verbose lifecycle discord-rpc-tool@1.0.0~package-win: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Programming\nodejs\discord-rpc-tool\node_modules\.bin;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\sampctl;C:\Program Files (x86)\nodejs\;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Users\alexr\AppData\Local\Programs\Python\Python37\;C:\Users\alexr\.cargo\bin;C:\Users\alexr\AppData\Local\Programs\Python\Python37;C:\Users\alexr\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\alexr\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\alexr\AppData\Local\Programs\Python\Python36\;C:\Users\alexr\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\alexr\AppData\Local\GitHubDesktop\bin;C:\Users\alexr\AppData\Local\Microsoft\WindowsApps;C:\lua;C:\Users\alexr\.dotnet\tools;C:\Users\alexr\AppData\Roaming\npm;
9 verbose lifecycle discord-rpc-tool@1.0.0~package-win: CWD: E:\Programming\nodejs\discord-rpc-tool
10 silly lifecycle discord-rpc-tool@1.0.0~package-win: Args: [ '/d /s /c',
10 silly lifecycle   'electron-packager . --overwrite --asar=true --platform=win32 --arch=ia32 --icon=assets/icons/win/icon.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName="Shopping List"' ]
11 silly lifecycle discord-rpc-tool@1.0.0~package-win: Returned: code: 1  signal: null
12 info lifecycle discord-rpc-tool@1.0.0~package-win: Failed to exec package-win script
13 verbose stack Error: discord-rpc-tool@1.0.0 package-win: `electron-packager . --overwrite --asar=true --platform=win32 --arch=ia32 --icon=assets/icons/win/icon.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName="Shopping List"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid discord-rpc-tool@1.0.0
15 verbose cwd E:\Programming\nodejs\discord-rpc-tool
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "package-win"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error discord-rpc-tool@1.0.0 package-win: `electron-packager . --overwrite --asar=true --platform=win32 --arch=ia32 --icon=assets/icons/win/icon.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName="Discord RPC Tool"`
22 error Exit status 1
23 error Failed at the discord-rpc-tool@1.0.0 package-win script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Here is my package.json:
```
{
  "name": "discord-rpc-tool",
  "version": "1.0.0",
  "description": "A tool for modifying your Discord Rich Presence.",
  "main": "index.js",
  "scripts": {
    "start": "electron .",
    "package-mac": "electron-packager . --overwrite --platform=darwin --arch=x64 --icon=assets/icons/mac/icon.icns --prune=true --out=release-builds",
    "package-win": "electron-packager . --overwrite --asar=true --platform=win32 --arch=ia32 --icon=assets/icons/win/icon.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName=\"Discord RPC Tool\"",
    "package-linux": "electron-packager . --overwrite --platform=linux --arch=x64 --icon=assets/icons/png/icon.png --prune=true --out=release-builds"
  },
  "keywords": [
    "discord",
    "discord-rpc",
    "rpc",
    "electron",
    "electron-latest",
    "drc",
    "discord-rich-presence"
  ],
  "author": "infin1tyy",
  "license": "ISC",
  "dependencies": {
    "discord-rich-presence": "0.0.8",
    "electron": "^5.0.1"
  },
  "devDependencies": {
    "electron-packager": "^13.1.1"
  }
}
```

**Comment by malept** [comment]
Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot help debug your app at this time. Instead, you should make sure your issue is not already answered in our [Frequently Asked Questions](https://github.com/electron-userland/electron-packager/blob/master/docs/faq.md) document, and consider using one of the [community forums](https://electronjs.org/community), as there are more people there available to answer questions. Troubleshooting suggestions can be found in our [contributing documentation](https://github.com/electron-userland/electron-packager/blob/master/CONTRIBUTING.md#debugging).
